### ISSUE TITLE
a11y issues

### ISSUE THREAD

**Issue by gbaudusseau** [w3c/mailing-list-archives#25]
Hey some accessibility issues with header on some proposals (contrast)

For example: https://w3c.github.io/mailing-list-archives/samples/message-proposal-gravatars.html

**Comment by tripu** [comment]
That's an unfortunate side-effect of the way we've integrated different proposals into `gh-pages`; my fault!
Thanks, @guibbs &mdash; I'm on it.

**Comment by tripu** [comment]
Actually, not an issue. Different proposals changed CSS slightly to achieve their goals. Final CSS will be combined from that of &ldquo;approved&rdquo; proposals. The low-contrast is an artifact that won't stay.
